# Generated by Django 3.0.7 on 2020-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='large',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
