# Generated by Django 3.0.7 on 2020-06-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200623_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='scilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('small', models.DecimalField(decimal_places=2, max_digits=10)),
                ('large', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
