# Generated by Django 3.0.7 on 2020-06-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_scilianpizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('small', models.DecimalField(decimal_places=2, max_digits=10)),
                ('large', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='regularPizza',
        ),
        migrations.DeleteModel(
            name='scilianPizza',
        ),
    ]
