# Generated by Django 3.0.7 on 2020-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200625_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
